<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Are you sure you want to log out_btn_b1065a</name>
   <tag></tag>
   <elementGuidId>6aa0f8d8-5db1-4988-b388-6beacb8839bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dialog[@id='my_modal_5']/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Yes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23b6f2ea-6d13-4d98-b6a5-7b0d9af2cb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mr-2 max-w-24 w-full h-10 bg-[#A46E40] border-[#A46E40] hover:bg-white hover:text-[#A46E40] text-white</value>
      <webElementGuid>b9f62019-365d-4d19-96aa-338353086d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>df0500aa-4ccd-41e2-b512-ba5bc59ad273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my_modal_5&quot;)/div[@class=&quot;modal-box&quot;]/div[@class=&quot;modal-action flex&quot;]/button[@class=&quot;btn mr-2 max-w-24 w-full h-10 bg-[#A46E40] border-[#A46E40] hover:bg-white hover:text-[#A46E40] text-white&quot;]</value>
      <webElementGuid>716821e4-4f7b-408f-aeaa-020c5ce9205d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dialog[@id='my_modal_5']/div/div/button</value>
      <webElementGuid>23c8380a-52f4-4af1-8301-754335cbb864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to log out?'])[1]/following::button[1]</value>
      <webElementGuid>e50cdfac-8078-4342-98c6-e59ad68cb10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fotogrit Coins'])[1]/following::button[1]</value>
      <webElementGuid>032b73c1-7bec-414d-97f0-362d69afd877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>b1f6d0ea-d556-4cf4-a0a5-7b11ec9514de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Account?'])[1]/preceding::button[2]</value>
      <webElementGuid>eb57a46e-3648-4d43-9612-fd73cae796fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>9ffad9e8-649d-4348-804b-123a330ef2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dialog/div/div/button</value>
      <webElementGuid>673cbc9a-37cb-451f-b676-90a7650d0de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>fb86f3e0-4f20-4f31-a903-e2fab8b77d44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
