<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__short_name</name>
   <tag></tag>
   <elementGuidId>a096792c-76e5-4c78-880b-b2f5022179d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='short_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;short_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Short Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16f682ae-b291-4be3-b3a3-5d71835e2046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b881ff63-dd56-48a5-9095-f0c5ed27252f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Short Name</value>
      <webElementGuid>455d0bad-6aa6-47af-b469-8f85c1c3a7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>short_name</value>
      <webElementGuid>5a34c3fa-1e67-4ed5-849b-9098771449b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-[44px] rounded-md border outline-none border-[#D5D7DA] px-3 py-2 hover:border-[#A46E40] focus:border-[#A46E40] hover:shadow-md focus:shadow-md transition-all duration-300 placeholder:font-articulat placeholder:text-sm</value>
      <webElementGuid>93091a92-8f49-45f0-9937-72f6c1364697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;md:min-h-[calc(100vh-172px)]&quot;]/div[@class=&quot;py-10&quot;]/div[@class=&quot;w-full bg-white flex justify-center items-center min-h-[calc(100vh-158px)] pt-16&quot;]/div[@class=&quot;max-w-[1120px] w-full px-5 py-[30px] text-center flex flex-col justify-between items-center gap-6 mr-0 xl:mr-[224px]&quot;]/div[@class=&quot;w-full&quot;]/form[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;mb-8 flex flex-col gap-6 md:flex-row lg:gap-[60px]&quot;]/div[@class=&quot;w-full space-y-6 border p-[16px] md:p-[30px] rounded-lg border-[#E9EAEB]&quot;]/div[@class=&quot;w-full&quot;]/div[1]/input[@class=&quot;w-full h-[44px] rounded-md border outline-none border-[#D5D7DA] px-3 py-2 hover:border-[#A46E40] focus:border-[#A46E40] hover:shadow-md focus:shadow-md transition-all duration-300 placeholder:font-articulat placeholder:text-sm&quot;]</value>
      <webElementGuid>beed291e-e6be-42f4-9cc6-d2e6e7b97890</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='short_name']</value>
      <webElementGuid>1289dd3b-ad8b-4ea3-843d-90b710186172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/form/div[2]/div[2]/div/div/input</value>
      <webElementGuid>8922eaea-89ca-4eb9-9d81-33e7cf39c055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>6178fd3c-6486-4255-a4d9-3306d3b9d917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Short Name' and @name = 'short_name']</value>
      <webElementGuid>35757d34-9859-4a23-88a4-7764e6453dd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
