<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_otp-input-1</name>
   <tag></tag>
   <elementGuidId>fc880db2-7634-4bc3-811f-77d6d4aac7b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp-input-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otp-input-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#otp-input-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5636921-e5e0-4b78-993f-66e572932187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp-input-1</value>
      <webElementGuid>c3a34fbe-7315-4741-a5c5-df5cef7a7f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>d03758aa-e315-4903-a162-0b1bc2b9f233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>8eaeca49-128f-41e7-8d87-7bdc97aadbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>1c802df7-1d07-402a-9760-7f548f00a2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>54764338-5e02-46d8-9781-f220a2d64dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0abd2e6-33a6-49e1-83e4-e31a5b3f387a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-w-16 w-full h-16 rounded-xl text-center  p-2 text-5xl font-articulat font-medium placeholder:text-[#D5D7DA] outline-none  flex justify-center items-center pt-[14px] border-[2px] hover:border-[#A46E40] focus:border-[#A46E40] hover:shadow-md focus:shadow-md transition-all duration-300 border-[#D5D7DA]text-black</value>
      <webElementGuid>96f98988-b63f-4fe6-ba1b-33c5fa4cb26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-input-1&quot;)</value>
      <webElementGuid>ae660c1d-d51a-43b7-93c7-a3a56673512b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp-input-1']</value>
      <webElementGuid>3fa416d2-bac8-42a7-9641-ba1556d30449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div[2]/input[2]</value>
      <webElementGuid>5afe7b4e-89ff-4382-b355-8c69c0261b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>d33f5177-71b3-480f-a09f-487ebc0a76bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp-input-1' and @type = 'tel' and @placeholder = '0']</value>
      <webElementGuid>e350b315-eccb-4e95-bcef-28c1db02725e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
