<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__email</name>
   <tag></tag>
   <elementGuidId>86aab474-f9f2-4514-9dbf-7b325b866dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c111d7fc-b0eb-43bc-aa9b-686e5f8a2b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5b73fffa-1389-4c2d-875c-f83a757d3380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-w-[353px] w-full h-[44px] text-[#636363] font-medium shadow-xs px-3 py-[10px] rounded-lg border border-[#D5D7DA] bg-transparent outline-none font-articulat hover:border-[#A46E40] focus:border-[#A46E40] hover:shadow-md focus:shadow-md transition-all duration-300</value>
      <webElementGuid>2ba82040-38a2-4839-8c6d-4eb00d35aaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e53c527d-cd23-46e8-b751-434dbdccc607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;md:min-h-[calc(100vh-172px)]&quot;]/div[@class=&quot;py-10&quot;]/div[@class=&quot;w-full bg-white flex justify-center items-center min-h-[calc(100vh-158px)]&quot;]/form[@class=&quot;max-w-[393px] sm:max-w-[393px] w-full px-5 py-5 border-none rounded-md bg-white&quot;]/div[@class=&quot;max-w-[334px] sm:max-w-[353px] w-full mb-4&quot;]/input[@class=&quot;max-w-[353px] w-full h-[44px] text-[#636363] font-medium shadow-xs px-3 py-[10px] rounded-lg border border-[#D5D7DA] bg-transparent outline-none font-articulat hover:border-[#A46E40] focus:border-[#A46E40] hover:shadow-md focus:shadow-md transition-all duration-300&quot;]</value>
      <webElementGuid>e073dd8e-37d2-43ed-9ab5-724468764545</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>fc1a2cb9-7da7-497f-8c7f-12f4bf99b7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/form/div[2]/input</value>
      <webElementGuid>9ac18857-79ef-42af-969a-26886147a5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5d887b8a-b37a-40e9-8b91-7532a32e3285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email']</value>
      <webElementGuid>a77bf08c-729b-43fe-8c1e-563b571dfd2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
